### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [sh-lee-prml/HierSpeechpp#11]
Hi, great project. Just curious why you decided to update the license from MIT to CC-BY-NC-SA?

**Comment by sh-lee-prml** [comment]
Thanks for your interest.

https://github.com/sh-lee-prml/HierSpeechpp/commit/c51b2140c1f9f15f483cd58705ff49a57e00aaaf#commitcomment-134193180

Now, I'm checking out the license of EXPRESSO. 

If there is no problem, we will have a plan to change the license to MIT license

Thanks!

**Comment by yiwei0730** [comment]
Sorry, let me ask a question, I'm a little curious.
As you said above, Non-Commercial is set because of the data set.
If I use my own data set to train with your program, will there be a problem with Non-Commercial ?

**Comment by sh-lee-prml** [comment]
> Sorry, let me ask a question, I'm a little curious. As you said above, Non-Commercial is set because of the data set. If I use my own data set to train with your program, will there be a problem with Non-Commercial ?

To reduce the misusage, we have restricted commercial usage for this model. 

I leave a message for EXPRESSO dataset now. 
If we could release the model under MIT License, we will change it soon.
 
We appreciate your understanding now.

**Comment by yiwei0730** [comment]
@sh-lee-prml  Sorry to bother you,  I want to ask if there is any response

**Comment by hayeong0** [comment]
🚩 We have changed to the MIT License.

**Comment by fakerybakery** [comment]
Thanks!
