### ISSUE TITLE
A question about the used F0 for SA and SR source filters

### ISSUE THREAD

**Issue by sellaProg** [sh-lee-prml/HierSpeechpp#17]
Hello, 
First of all, thank you for your work, I am enjoying reading your paper and finding that we share few ideas :) 
I am curious for the F0s fed to the speaker agnostic and speaker related source filters during training, were do they come from? from the  audio after perturbation? or the audio before perturbation or the SA F0 comes from the audio after perturbation and the SR F0 comes from the original audio?

Thank you.

**Comment by sh-lee-prml** [comment]
Hi Thanks for your interest!

Both F0s are same and they are from the original speech. We do not perturb the audio when extracting F0s. 

Thanks!

**Comment by sellaProg** [comment]
Interesting, Thank you.
