### ISSUE TITLE
That's great!

### ISSUE THREAD

**Issue by 397688551** [sh-lee-prml/HierSpeechpp#22]
It's really good, looking forward to the Chinese model. When will the open source code allow us to train ourselves?

**Comment by mysxs** [comment]
hoping for train code

**Comment by igbeller** [comment]
@sh-lee-prml is project abandoned?

**Comment by sh-lee-prml** [comment]
Please refer to this [issue](https://github.com/sh-lee-prml/HierSpeechpp/issues/6)

I have not received any responses yet from the Journal.
