### ISSUE TITLE
Do you use biT-flow in ttv?

### ISSUE THREAD

**Issue by segmentationFaults** [sh-lee-prml/HierSpeechpp#24]
Thank you for your great previous reply. I have suceessfully finetune your pretrained model. Do you use biT-flow in ttv?

**Comment by sh-lee-prml** [comment]
Hi!

Glad to hear that :)

I have not used BiT-Flow yet in ttv. 

Actually, I think that it could improve the performance like NaturalSpeech. 

However, I do not have an exact alignment between text and speech so I do not use BiT-Flow in TTV.

If you can utilize an external aligner to get a duration before training, I recommend using BiT-Flow in TTV! 

Thanks

**Comment by segmentationFaults** [comment]
I don't have a accurate aligner. the alignment of pretrained ttv is OK?

**Comment by sh-lee-prml** [comment]
I don't recommend using the alignment of pretrained TTV. The alignment of MAS is not accurate.

An external aligner such as MFA is good for that.

However, if you hope to use the external aligner, you may need to change some modules in ttv.

In this case(when using an external aligner), I recommend using frame prior network of Period VITS with length regulator. 

Period VITS: https://arxiv.org/pdf/2210.15964.pdf

Thanks
