### ISSUE TITLE
would it be possible to provide a version without restrictive training data

### ISSUE THREAD

**Issue by xiaolongtangbao** [sh-lee-prml/HierSpeechpp#34]
Thank you for sharing the code and checkpoints! the results are great! Would it be possible to have a version trained without the expresso dataset or any other non-commercial dataset?

**Comment by sh-lee-prml** [comment]
Hi

You can use some checkpoints which are trained with LibriTTS460 or LibriTTS960

https://drive.google.com/drive/u/2/folders/1-L_90BlCkbPyKWWHTUjt5Fsu3kz0du0w

Thanks!
