### ISSUE TITLE
Missing keys in checkpoint file

### ISSUE THREAD

**Issue by arsm** [sh-lee-prml/HierSpeechpp#37]
Thank you for your excellent work! I'm currently working on fine-tuning the TTV model with a non-English dataset. I've downloaded the 'ttv_lt960_ckpt.pth' and attempted to load it using utils.load_checkpoint function in the 'train_ttv_v1.py' to initiate the model. However, the checkpoint doesn't include the required keys like 'optimizer', 'model', 'learning_rate', and 'iteration', making it impossible to load. Could you please guide me on what might be missing or if there are any additional steps I need to take?

**Comment by sh-lee-prml** [comment]
Hi!

Here is a checkpoint including all.

https://drive.google.com/file/d/1ZCgvuBFAmY39r8dENWdOglXyp6iVmati/view?usp=drive_link

Thanks!

**Comment by arsm** [comment]
Thank you so much, @sh-lee-prml. I appreciate it.
