### ISSUE TITLE
Hi, Can you please provide instructions for training process and dataset requirements?

### ISSUE THREAD

**Issue by Oleksandr2505** [sh-lee-prml/HierSpeechpp#41]

**Comment by sh-lee-prml** [comment]
Hi

Could you refer this page?

https://github.com/sh-lee-prml/HierSpeechpp/tree/main/ttv_v1

Please follow above instructions with libritts dataset or your dataset 
You have to downsampe the dataset to 16 kHz before preprocessing!.



Thanks

**Comment by Oleksandr2505** [comment]
> Hi
> 
> Could you refer this page?
> 
> https://github.com/sh-lee-prml/HierSpeechpp/tree/main/ttv_v1
> 
> Please follow above instructions with libritts dataset or your dataset You have to downsampe the dataset to 16 kHz before preprocessing!.
> 
> Thanks

Thank you!
