### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by pawanhv** [sh-lee-prml/HierSpeechpp#6]
Hi,
Will the training code be released to test it on our own datasets? 

Pavan

**Comment by sh-lee-prml** [comment]
Thanks for your interest

We will have a plan to share the training code after paper acceptance or getting good reviews. We would appreciate your understanding. 

Thanks
Sang-Hoon

**Comment by pawanhv** [comment]
Ok thanks, good implementation thought 👍 do you have a timeline for the paper review ?

**Comment by jupinter** [comment]
How is everything going on?[微笑]

**Comment by Pydataman** [comment]
mark

**Comment by mysxs** [comment]
Hope to go online training code as soon as possible~

**Comment by zhuangzhuangliu2345** [comment]
How is everything going on? Looking forward to the release.

**Comment by youralmight** [comment]
mark

**Comment by hayeong0** [comment]
### TTV training code

We have updated the **Text-To-Vec** training code. 
The training code for the speech synthesizer will be made public after the journal process of this research is completed.
However, you can use a pre-trained our hierspeechpp synthesizer and train TTV with your own dataset.
Our speech synthesizer is powerful in zero-shot, so after TTV training, it can synthesize high-quality speech.
Thank you for taking an interest in our work! :)
